{% set version = "0.8.0" %}
{% set ros_industrial_cmake_boilerplate_version = "0.5.3" %}
{% set opw_kinematics_version = "0.5.0" %}
{% set tesseract_version = "0.21.5" %}
{% set tesseract_planning_version = "0.21.6" %}
{% set tesseract_python_version = "0.4.0" %}
{% set trajopt_version = "0.7.2" %}
{% set descartes_light_version = "0.4.2" %}
{% set ruckig_version = "0.12.2" %}

package:
  name: tesseract-robotics-superpack
  version: {{ version }}

source:
  - url: https://github.com/ros-industrial/ros_industrial_cmake_boilerplate/archive/refs/tags/{{ ros_industrial_cmake_boilerplate_version }}.tar.gz
    folder: src/ros_industrial_cmake_boilerplate
  - url: https://github.com/Jmeyer1292/opw_kinematics/archive/refs/tags/{{ opw_kinematics_version }}.tar.gz
    folder: src/opw_kinematics
  - url: https://github.com/tesseract-robotics/tesseract/archive/refs/tags/{{ tesseract_version }}.tar.gz
    folder: src/tesseract
  - url: https://github.com/tesseract-robotics/trajopt/archive/refs/tags/{{ trajopt_version }}.tar.gz
    folder: src/trajopt
    patches:
      - trajopt-patch.patch
  - url: https://github.com/swri-robotics/descartes_light/archive/refs/tags/{{ descartes_light_version }}.tar.gz
    folder: src/descartes_light
  - url: https://github.com/tesseract-robotics/tesseract_planning/archive/refs/tags/{{ tesseract_planning_version }}.tar.gz
    folder: src/tesseract_planning
  - url: https://github.com/pantor/ruckig/archive/refs/tags/v{{ ruckig_version }}.tar.gz
    folder: src/ruckig
    patches:
      - ruckig-install-header-files.patch
  - url: https://github.com/tesseract-robotics/tesseract_python/archive/refs/tags/{{ tesseract_python_version }}.tar.gz
    folder: src
    patches:
      - tesseract-python-pip-install.patch

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gtest
    - gmock
    - cmake
    - ninja # [win]
    - make # [linux]
    - pkg-config
    - swig ==4.1.1
    - colcon-common-extensions 
    - lcov
    - {{ cdt('mesa-libgl-devel') }}    # [linux]
    - {{ cdt('mesa-dri-drivers') }}    # [linux]
  host:
    - boost-cpp 
    - eigen 
    - tinyxml2
    - console_bridge
    - assimp
    - urdfdom
    - fcl
    - octomap 
    - orocos-kdl 
    - pcl
    - gtest
    - gmock
    - pkg-config 
    - osqp 
    - osqp-eigen 
    - xz
    - ompl
    - flann
    - jsoncpp
    - taskflow 
    - python
    - numpy
    - pip
    - yaml-cpp
    - bullet-cpp
    - xorg-libx11    # [unix]
    - xorg-libxext   # [unix]
  run:
    - boost-cpp
    - eigen 
    - tinyxml2
    - console_bridge
    - assimp
    - urdfdom
    - fcl
    - octomap 
    - orocos-kdl 
    - pcl
    - gtest
    - gmock
    - osqp 
    - osqp-eigen 
    - xz
    - jsoncpp
    - ompl
    - taskflow 
    - python
    - numpy
    - yaml-cpp
    - bullet-cpp
    - xorg-libx11    # [unix]
    - xorg-libxext   # [unix]

test:
  files:
    - test_tesseract_task_composer.py
    - run_test_tesseract_python.sh # [unix]
    - run_test_tesseract_python.bat # [win]
  requires:
    - pytest
  commands:
    - ./run_test_tesseract_python.sh # [unix]
    - run_test_tesseract_python.bat # [win]

build:
  skip: true # [py<38]
  number: 0

about:
  home: https://github.com/ros-industrial-consortium/tesseract
  summary: Tesseract robotics motion planning framework


